# Generated by Django 4.0 on 2022-01-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
    ]
