# Generated by Django 4.0 on 2022-01-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_address_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
    ]
